// <auto-generated />
namespace SatisSimilasyon.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class firstCheckIn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstCheckIn));
        
        string IMigrationMetadata.Id
        {
            get { return "202010100917408_firstCheckIn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
