// <auto-generated />
namespace SatisSimilasyon.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Duzenleme1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Duzenleme1));
        
        string IMigrationMetadata.Id
        {
            get { return "202010241002162_Duzenleme1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
